apiVersion: v1
kind: Service
metadata:
  name: hrmanagement-service
spec:
  type: NodePort # Expone el servicio fuera del cluster
  selector:
    app: hrmanagement-api # Debe coincidir con el label del Deployment
  ports:
  - port: 80
    targetPort: 8080 # El puerto 8080 del contenedor