apiVersion: v1
kind: Secret
metadata:
  name: hrmanagement-secrets
type: Opaque
stringData:
  sa-password: "PasswordFuerte123!"
  db-connection: "Server=mssql-service;Database=HRManagementDb;User Id=sa;Password=PasswordFuerte123!;TrustServerCertificate=True;"
